### PR TITLE
Append to classpath not safe without separator

### PR DESCRIPTION
**Pull request by jlberner**
It is not safe to append a new path to the CLASSPATH environment variable without a path separator that is suitable for the platform. I could not think of a good/concise way to determine the appropriate path separator, but it should not be necessary to have anything remain in it, so changing from append to assignment.

This resolves the "Class t16subclass not found" outstanding issue.

### CODE REVIEW

**Comment by mohawk2** [comment]
Or, it would work to use something like:
```perl
$ENV{CLASSPATH} = join $Config{path_sep}, grep defined, $ENV{CLASSPATH}, File::Spec->catfile(qw(t t16subclass.jar));
```

Please update to that and we can merge and make a release!

**Comment by jlberner** [comment]
Update done as requested. Thanks!

**Review by mohawk2 — APPROVED** [review]
Thank you!

**Comment by mohawk2** [comment]
This works a lot better if one goes ahead and loads `Config` and `File::Spec` first (and actually tests one's changes).

**Comment by mohawk2** [comment]
Released as 0.67!

**Pull request merged**
