### PR TITLE
Fix SDKMAN! installation on OSX

### PR DESCRIPTION
**Pull request by TisonKun**
Use `eval` to resolve dependency issue, we assume `J2SDK_BIN` a scalar not array. If use candidates, more logic should modify.

### CODE REVIEW

**Comment by TisonKun** [comment]
ping @mohawk2

**Comment by TisonKun** [comment]
ping @mohawk2 could you take a look when you are free?

**Comment by TisonKun** [comment]
Hi @mohawk2 I would close this one as no response in this week.

**Comment by mohawk2** [comment]
Sorry for delay. Can you help me understand why you've moved the check for `javac` etc?

**Comment by TisonKun** [comment]
I have no idea...maybe close and if anyone else interested in he can always open a new pull request.

**Pull request closed without merging**
